"""Run a batch of submission variants in parallel.

Kaggle allows five submissions a day, and each one needs a completed notebook
version. Kernels with different slugs run in parallel, so one copy per
configuration turns a day of experiments into roughly one run of wall clock.
Scoring takes 7-19 hours, so a day's batch is launched together and read
together the next day.

    # build notebooks/batch/<slug>/ for each entry and run them
    python scripts/batch.py launch --config experiments/configs/batch01.json

    # submit the completed ones (normally done by scripts/cycle.py)
    python scripts/batch.py submit --config experiments/configs/batch01.json

A config maps slugs to {"base": "infer"|"geofusion", "note": "...",
"env": {"BIOHUB_*": "..."}}.
"""

from __future__ import annotations

import argparse
import ast
import json
import pathlib
import re
import subprocess
import sys
import time

for _s in (sys.stdout, sys.stderr):
    if hasattr(_s, "reconfigure"):
        _s.reconfigure(encoding="utf-8")

ROOT = pathlib.Path(__file__).resolve().parent.parent
# Notebooks a variant can be built from, chosen by "base" (default: infer).
# Both share the same layout: cell 1 sets the environment, cell 2 guards it.
BASES = {
    "infer": ROOT / "notebooks" / "infer" / "biohub-infer.ipynb",
    "geofusion": ROOT / "notebooks" / "geofusion" / "biohub-geofusion.ipynb",
    # k953 has no header cell (settings are in cell 0); build() inserts one.
    "k953": ROOT / "notebooks" / "k953" / "biohub-k953.ipynb",
}
OUT_DIR = ROOT / "notebooks" / "batch"
COMP = "biohub-cell-tracking-during-development"

sys.path.insert(0, str(ROOT / "scripts"))
from _kaggle_user import kaggle_username  # noqa: E402


def _fmt(value: str) -> str:
    """Literal for the guard's expected value: numbers bare, strings quoted."""
    try:
        float(value)
    except (TypeError, ValueError):
        return '"' + str(value) + '"'
    return str(value)


def build(slug: str, spec: dict, user: str) -> pathlib.Path:
    """Copy the base notebook with this variant's settings."""
    folder = OUT_DIR / slug
    folder.mkdir(parents=True, exist_ok=True)

    base = spec.get("base", "infer")
    base_nb = BASES[base]
    nb = json.loads(base_nb.read_text(encoding="utf-8"))
    if base == "k953":
        nb["cells"].insert(0, {"cell_type": "code", "metadata": {}, "execution_count": None,
                               "outputs": [], "source": []})
    for _c in nb["cells"]:
        if isinstance(_c.get("source"), str):
            _c["source"] = _c["source"].splitlines(keepends=True)

    # The forked preamble assigns ~47 BIOHUB_* variables unconditionally,
    # which silently discards anything set in the first cell. Rewriting each
    # one to setdefault is what makes the prediction-stage knobs
    # (DET_THRESHOLD, ILP_*) reachable at all.
    c1 = "".join(nb["cells"][1]["source"])
    # Trailing comments stay outside the call: `= "0"  # note` -> `setdefault("K", "0")  # note`.
    c1 = re.sub(
        r'os\.environ\["(BIOHUB_[A-Z0-9_]+)"\]\s*=\s*("[^"\n]*"|\'[^\'\n]*\'|[^#\n]*?)[ \t]*(#[^\n]*)?$',
        lambda m: f'os.environ.setdefault("{m.group(1)}", {m.group(2).strip()})'
        + (f"  {m.group(3)}" if m.group(3) else ""),
        c1,
        flags=re.M,
    )
    nb["cells"][1]["source"] = [l + chr(10) for l in c1.split(chr(10))]

    env = dict(spec.get("env", {}))

    # The fork guards eight settings in cell 2 and raises on any mismatch,
    # which is what blocked DET_THRESHOLD and the ILP weights. Keep the
    # guard - it catches genuine typos - but move its expectation for the
    # keys being overridden here.
    c2 = "".join(nb["cells"][2]["source"])
    for _k, _v in env.items():
        c2 = re.sub(r'("' + _k + r'":\s*)[^,\n]+', lambda m: m.group(1) + _fmt(_v), c2)
    nb["cells"][2]["source"] = [l + chr(10) for l in c2.split(chr(10))]
    # Submission runs never use the built-in validator/sweep: the settings are fixed here.
    env.setdefault("BIOHUB_VALIDATOR_ENABLE", "0")

    lines = [
        "# Biohub / submission run",
        "#",
        f"# {spec.get('note', '')}".rstrip(),
        "#",
        f"# Generated by scripts/batch.py from notebooks/{base}. The built-in",
        "# validator and sweep are off: the configuration is fixed here, and",
        "# leaving them on would add ~80 minutes to every run.",
        "",
        "import os",
        "",
        "BIOHUB_OVERRIDES: dict[str, str] = {",
    ]
    lines += [f'    "{k}": "{v}",' for k, v in env.items()]
    lines += [
        "}",
        "",
        "for _key, _value in BIOHUB_OVERRIDES.items():",
        "    os.environ[_key] = str(_value)",
        "",
        'print("overrides:", BIOHUB_OVERRIDES)',
    ]
    nb["cells"][0]["source"] = [l + "\n" for l in lines]
    # Optional code patches: {"patches": [[old, new], ...]}. Each `old` must occur
    # exactly once across the code cells, so a stale anchor fails here, not on Kaggle.
    for _old, _new in spec.get("patches", []):
        _hits = [c for c in nb["cells"] if _old in "".join(c["source"])]
        _count = sum("".join(c["source"]).count(_old) for c in nb["cells"])
        if _count != 1:
            raise SystemExit(f"{slug}: patch anchor found {_count} times: {_old[:60]!r}")
        _cell = _hits[0]
        _text = "".join(_cell["source"]).replace(_old, _new)
        _cell["source"] = _text.splitlines(keepends=True)

    # Optional: drop every cell after the one containing this marker (e.g. stop
    # after prediction), then append extra code cells.
    _marker = spec.get("truncate_after")
    if _marker:
        _idx = [i for i, c in enumerate(nb["cells"]) if _marker in "".join(c["source"])]
        if len(_idx) != 1:
            raise SystemExit(f"{slug}: truncate marker found in {len(_idx)} cells")
        nb["cells"] = nb["cells"][: _idx[0] + 1]
    for _extra in spec.get("append_cells", []):
        nb["cells"].append({"cell_type": "code", "metadata": {}, "execution_count": None,
                            "outputs": [], "source": _extra.splitlines(keepends=True)})

    # Catch rewrite mistakes locally instead of on a GPU run.
    for _i, _cell in enumerate(nb["cells"]):
        if _cell.get("cell_type") != "code":
            continue
        _src = "".join(_cell["source"])
        _src = "\n".join("" if l.lstrip().startswith(("!", "%")) else l for l in _src.split("\n"))
        try:
            ast.parse(_src)
        except SyntaxError as exc:
            raise SystemExit(f"{slug}: cell {_i} does not parse after rewriting: {exc}")
    (folder / f"{slug}.ipynb").write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding="utf-8")

    meta = json.loads((base_nb.parent / "kernel-metadata.json").read_text(encoding="utf-8"))
    meta.pop("id_no", None)
    meta.update({"id": f"{user}/{slug}", "title": slug, "code_file": f"{slug}.ipynb"})
    # Extra inputs, e.g. the output of our own head-training notebook.
    meta["kernel_sources"] = list(meta.get("kernel_sources", [])) + list(spec.get("kernel_sources", []))
    meta["dataset_sources"] = list(meta.get("dataset_sources", [])) + list(spec.get("dataset_sources", []))
    (folder / "kernel-metadata.json").write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
    return folder


def kernel_version(user: str, slug: str) -> int | None:
    """Return the `kaggle kernels status` output for the kernel."""
    out = subprocess.run(
        ["kaggle", "kernels", "status", f"{user}/{slug}"],
        capture_output=True, text=True, encoding="utf-8", errors="replace",
    ).stdout
    return out


def already_submitted(api) -> set[str]:
    """Slugs already submitted (each submission message starts with its slug)."""
    done: set[str] = set()
    try:
        for sub in api.competition_submissions(COMP, page_size=200):
            d = sub.to_dict() if hasattr(sub, "to_dict") else {}
            desc = str(d.get("description") or "")
            status = str(d.get("status") or "")
            if "ERROR" in status.upper():
                continue
            head = desc.split(":")[0].strip()
            if head:
                done.add(head)
    except Exception as exc:
        print(f"  could not read submissions (duplicate check skipped): {exc}")
    return done


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("action", choices=["launch", "submit", "status"])
    ap.add_argument("--config", required=True)
    args = ap.parse_args()

    user = kaggle_username()
    cfg_path = pathlib.Path(args.config)
    specs = json.loads(cfg_path.read_text(encoding="utf-8"))

    for slug, spec in specs.items():
        if args.action == "launch":
            folder = build(slug, spec, user)
            print(f"=== {slug} ===", flush=True)
            # Kaggle allows only two concurrent batch GPU sessions. Rather than
            # giving up, wait for a slot: a submission run is ~35 min, so five
            # of them come out to roughly 1.5 h of wall clock.
            for _attempt in range(30):
                r = subprocess.run(
                    [sys.executable, str(ROOT / "scripts" / "push_kernel.py"),
                     "-p", str(folder), "--run"],
                    capture_output=True, text=True,
                    # push_kernel.py prints UTF-8; decode it explicitly so a
                    # non-UTF-8 console default cannot lose the output.
                    encoding="utf-8", errors="replace",
                )
                out = (r.stdout or "") + (r.stderr or "")
                print(out.strip()[-200:], flush=True)
                if "Maximum batch GPU session count" not in out:
                    # A kernel that errored once gets a bumped version on the next
                    # push, so submitting version 1 blindly fails with
                    # "Did not find provided Notebook Output File". Record what
                    # was actually pushed.
                    m = re.search(r"version:\s*(\d+)", out)
                    if m and int(m.group(1)) > 0:
                        spec["version"] = int(m.group(1))
                        cfg_path.write_text(
                            json.dumps(specs, indent=2, ensure_ascii=False) + chr(10),
                            encoding="utf-8",
                        )
                        print(f"  recorded version {m.group(1)}", flush=True)
                        # Kaggle does not expose the GPU quota, so every run is
                        # booked here at the measured light-run cost (27 min).
                        ledger = ROOT / "experiments" / "configs" / "gpu_ledger.json"
                        lg = json.loads(ledger.read_text(encoding="utf-8"))
                        lg["runs"].append({"kernel": slug, "version": int(m.group(1)),
                                           "hours": 0.45, "note": "auto: light run"})
                        ledger.write_text(json.dumps(lg, indent=2, ensure_ascii=False) + chr(10),
                                          encoding="utf-8")
                    break
                print("  waiting for a free GPU session (10 min)", flush=True)
                time.sleep(600)
        elif args.action == "status":
            print(f"{slug:24s} {kernel_version(user, slug).strip()[-40:]}")
        else:
            st = kernel_version(user, slug)
            if "COMPLETE" not in st:
                print(f"{slug:24s} not complete, skipped: {st.strip()[-40:]}")
                continue
            from kaggle.api.kaggle_api_extended import KaggleApi
            api = KaggleApi(); api.authenticate()
            # Only five submissions a day: never spend one on a slug twice.
            if slug in already_submitted(api):
                print(f"{slug:24s} already submitted, skipped")
                continue
            ver = spec.get("version", 1)
            try:
                api.competition_submit_code(
                    file_name="submission.csv",
                    message=f"{slug}: {spec.get('note', '')}",
                    competition=COMP,
                    kernel=f"{user}/{slug}",
                    kernel_version=ver,
                )
                print(f"{slug:24s} submitted (v{ver})")
            except Exception as e:
                resp = getattr(e, "response", None)
                msg = resp.json().get("error", {}).get("message") if resp is not None else str(e)
                print(f"{slug:24s} submission failed: {msg}")


if __name__ == "__main__":
    main()
